config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'tasks#index'
  resources :tasks
  resources :users, only: [:new, :create, :show]#:edit, :update足したい
  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :label_tasks, dependent: :destroy
  has_many :tasks, through: :label_task #source: :task
end
#アソシ3　テキスト

app/models/label_task.rb
class LabelTask < ApplicationRecord
  belongs_to :label
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  has_many :label_task, dependent: :destroy
  has_many :labels, through: :label_task

  validates :title, presence: true
  validates :content, presence: true

  #enum status・priority用
  enum status: {"未着手":0, "着手中":1, "完了":2}
  enum priority: { 低: 0, 中: 1, 高: 2}
  # enum :status, [ :draft, :published, :archived, :trashed ]

  scope :scope_title, -> (title){ where('title LIKE ?', "%#{title}%") }
  scope :scope_status, -> (status){ where(status: status) }
  scope :scope_label, -> (label_ids){ where(id: LabelTask.where(label_id: label_ids).pluck(:task_id))}

  scope :default_sort, -> { order(created_at: :desc) }
  scope :sort_expired_at, -> {order(expired_at: :desc)}
  scope :sort_priority, -> { order(priority: :desc) }
end

app/models/task_spec.rb
require 'rails_helper'

RSpec.describe 'タスクモデル機能', type: :model do
  describe 'バリデーションのテスト' do
    context 'タスクのタイトルが空の場合' do
      it 'バリデーションにひっかる' do
        task = Task.new(title: '', content: '失敗テスト1')
        expect(task).not_to be_valid
      end
    end
    context 'タスクの詳細が空の場合' do
      it 'バリデーションにひっかかる' do
        task = Task.new(title: '失敗テスト2', content: '')
        expect(task).not_to be_valid
      end
    end
    context 'タスクのタイトルと詳細に内容が記載されている場合' do
      it 'バリデーションが通る' do
        task = Task.new(title: '成功1', content: '成功2')
        expect(task).to be_valid
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :admin_exist_check
  before_update :admin_update_exist

  has_many :tasks
  has_secure_password

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
             format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }

  validates :password, length: { minimum: 6 }


  def admin_exist_check
    if User.where(admin: true).count <= 1 && self.admin == true
      throw(:abort)
    end
  end

  def admin_update_exist
    if User.where(admin: true).count == 1 && self.admin == false
      throw(:abort)
    end
  end




end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :if_not_admin

def index
  @users = User.all.includes(:tasks)
end

def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    redirect_to user_path(@user.id)
  else
    render :new
  end
end

def edit
  @user = User.find(params[:id])
end

def update
  @user = User.find(params[:id])
  if @user.update(user_params)
      flash[:notice] = "情報を編集しました！"
      redirect_to tasks_path
  else
      render :edit
  end
end

def show
  @user = User.find(params[:id])
end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "ユーザーをを削除しました"
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end



  def if_not_admin
    unless current_user.admin?
        flash[:notice] = "管理者以外はアクセスできません"
        redirect_to tasks_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required
  #private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create ]

  def new
    redirect_to user_path(current_user.id) if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
      # ログイン成功した場合
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = current_user.tasks

    if params[:sort_expired_at]
      @tasks = @tasks.all.sort_expired_at.page(params[:page])
    elsif params[:sort_priority]
      @tasks = @tasks.all.sort_priority.page(params[:page])
    else
      @tasks = @tasks.all.default_sort.page(params[:page])
    end

    #タイトルとステータス絞り込み
    if params[:task].present?
      if params[:task][:title].present? && params[:task][:status].present?
        @tasks = @tasks.scope_title(params[:task][:title])
        @tasks = @tasks.scope_status(params[:task][:status])
      elsif params[:task][:title].present?
        @tasks = @tasks.scope_title(params[:task][:title])
      elsif params[:task][:status].present?
        @tasks = @tasks.scope_status(params[:task][:status])
      elsif params[:task][:label_ids].present?
        @tasks = @tasks.scope_label(params[:task][:label_ids])
      # elsif params[:label_id].present?
      #   @tasks = @tasks.joins(:labels).where(labels: { id: params[:label_id] })
      end
    end
  end


  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task = current_user.tasks.build(task_params)
    if @task.save
    # binding.pry
      flash[:notice] = "タスクを作成しました！"
      redirect_to tasks_path
    else
      render :new
    end
  end

  def show
    @task = Task.find(params[:id])
    labels = LabelTask.where(task_id: @task.id).pluck(:label_id)
    @labels = Label.find(labels)######################################1/31 01:16
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:notice] = "タスクを編集しました！"
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice] = "タスクを削除しました！"
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:content, :title, :expired_at, :status, :priority, { label_ids: [] })
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      flash[:notice] = "権限がありません"
      redirect_to  tasks_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
      current_user.present?
  end

  def admin?
    current_user.admin?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>ユーザー編集</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_with(model: [:admin, @user], local: true) do |f| %>
<div class = "name" >
  <%= f.label :名前 %>
  <%= f.text_field :name %>
</div>

<div class = "email" >
  <%= f.label :メールアドレス %>
  <%= f.email_field :email %>
</div>

<div class = "email" >
  <%= f.label :管理者権限 %>
  <%= f.select :admin, [["一般ユーザー","false"],["管理者ユーザー","true"]] %>
</div>

<div class = "password" >
  <%= f.label :パスワード %>
  <%= f.password_field :password %>
</div>

<div class = "password_confirmation" >
  <%= f.label :確認用パスワード %>
  <%= f.password_field :password_confirmation %>
</div>

  <%= f.submit "登録" %>
<% end %>

app/views/admin/users/index.html.erb
<h1>ユーザー管理画面</h1>
<%= link_to 'ユーザーを登録する',new_admin_user_path %>



<table>
    <tr>
      <th>ユーザー名</th>
      <th>メールアドレス</th>
      <th>タスク数</th>
      <th>管理権限</th>
      <th>詳細</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.tasks.count %></td>
        <td><%= user.admin %></td>
        <td><%= link_to '詳細', admin_user_path(user) %></td>
        <td><%= link_to '編集', edit_admin_user_path(user) %></td>
        <td><%= link_to '削除', admin_user_path(user), method: :delete, date: { confirm: '本当に削除してもいいですか？' } %></td>
      </tr>
    <% end %>
</table>

app/views/admin/users/new.html.erb
<h1>新規登録</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_with(model: [:admin, @user], local: true) do |f| %>
<div class = "name" >
  <%= f.label :名前 %>
  <%= f.text_field :name %>
</div>

<div class = "email" >
  <%= f.label :メールアドレス %>
  <%= f.email_field :email %>
</div>

<div class = "email" >
  <%= f.label :管理者権限 %>
  <%= f.select :admin, [["一般ユーザー","false"],["管理者ユーザー","true"]] %>
</div>

<div class = "password" >
  <%= f.label :パスワード %>
  <%= f.password_field :password %>
</div>

<div class = "password_confirmation" >
  <%= f.label :確認用パスワード %>
  <%= f.password_field :password_confirmation %>
</div>

  <%= f.submit "登録" %>
<% end %>

app/views/admin/users/show.html.erb
<h2><%= @user.name %>さんのタスク一覧</h2>
  <table>
    <tr>
      <th>タスク名</th>
      <th>内容</th>
      <th>終了期限</th>
      <th>登録日時</th>
      <th>ステータス</th>
      <th>優先順位</th>
    </tr>
    <% @user.tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.expired_at %></td>
        <td><%= task.created_at %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
      </tr>
    <% end %>
  </table>
<%= link_to '戻る', admin_users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FixManyoukadai</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to 'profile', user_path(current_user.id) %>
      <%= link_to 'Logout', session_path(current_user.id), method: :delete %>
      <%= link_to "管理者画面",admin_users_path,class:"login" if admin? %>
    <% else %>
      <%= link_to 'Sign up', new_user_path %>
      <%= link_to 'Login', new_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>

<div class="task_field">
  <%= form.label 'タスク名' %>
  <%= form.text_field :title %>
</div>

<div class="task_field">
  <%= form.label '内容' %>
  <%= form.text_area :content %>
</div>

<div class="task_field">
  <%= form.label '終了期限' %>
  <%= form.datetime_field :expired_at %>
</div>

<div class="task_field">
  <%= form.label 'ステータス' %>
  <%= form.select :status, Task.statuses.keys, { include_blank: "選択してください"} %>
</div>

<div class="task_field">
  <%= form.label '優先順位' %>
  <%= form.select :priority, Task.priorities.keys, { include_blank: "選択してください"} %>
</div>

<div class="task_field">
    <%= form.label 'ラベル' %>
    <br>
    <%= form.collection_check_boxes(:label_ids, Label.all, :id, :label_name) %>
</div>

  <%= form.submit"登録する" %>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスクの編集</h1>
<%= render 'form' %>
<%= link_to '詳細', @task %> 
<%= link_to '一覧', tasks_path %>

app/views/tasks/index.html.erb
<h1><%= link_to "Task一覧", tasks_path %></h1>

<!--検索フォーム-->
<%= form_with(scope: :task, local: true, method: :get, url: tasks_path) do |form| %>
  <div class ="search_form">
  <%= t('.title') %>
  <%= form.search_field :title %>
  <%= t('.status') %>
  <%= form.select :status, [["未着手", 0], ["着手中", 1], [ "完了", 2]], include_blank: '選択してください', class: 'form-control', required: true %>
  <%= t('.label_name')%>
  <%= form.select( "label_ids", Label.pluck(:label_name, :id), { include_blank: '選択してください' }) %>
  <%= form.submit '検索', class: 'btn btn-primary' %>
  </div>
<% end %>

<div class="btn-group">
<button type="button" class="btn btn-light"><%= link_to "終了期限でソートする", tasks_path(sort_expired_at: "true") %></button>
<button type="button" class="btn btn-light"><%= link_to '優先順位でソート', tasks_path(sort_priority: "true") %></button>
<button type="button" class="btn btn-light"><%= link_to "作成日でソートする", tasks_path(default_sort: "true") %></button>
</div>

<table class="table">
<head>
  <th><%= t('.name') %></th>
  <th><%= t('.title') %></th>
  <th><%= t('.content') %></th>
  <th><%= t('.label_name') %></th>
  <th><%= t('.expired_at') %></th>
  <th><%= t('.status') %></th>
  <th><%= t('.priority') %></th>
  <th><%= t('.created_at') %></th>
  <th></th>
  <th></th>
  <th></th>
</head>

<body>
<% @tasks.each do |task| %>
  <tr class = "task_row">
      <td><%= task.user.name %></td>
      <td><%= task.title %></td>
      <td><%= task.content %></td>
      <td><% task.labels.each do |label| %>
      <%= label.label_name %>
      <% end %></td>
      <td><%= task.expired_at.strftime("%Y-%m-%d %H:%M") %></td>
      <td><%= task.status %></td>
      <td><%= task.priority %></td>
      <td><%= task.created_at.strftime("%Y-%m-%d %H:%M") %></td>
  <td><%= link_to '詳細', task_path(task.id), class:"btn btn-outline-primary" %></td>
  <td><%= link_to '編集', edit_task_path(task.id),class:"btn btn-outline-success" %></td>
  <td><%= link_to '削除', task_path(task.id), method: :delete, data: { confirm: '本当に削除しますか？'}, class:"btn btn-outline-danger" %></td>
  </tr>
<% end %>
</body>
</table>

<%= paginate @tasks %>
<button type="button" class="btn btn-light"><%=link_to '新規作成', new_task_path %></button>

app/views/tasks/new.html.erb
<h2>新規タスク入力</h2>
<%= render 'form' %>
<%= link_to '戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1></h1>
<br>
<b>タスク名</b>
<%= @task.title %>
<br>

<b>タスク詳細</b>
<%= @task.content %>
<br>

<b>終了期限</b>
<%= @task.expired_at.strftime("%Y-%m-%d %H:%M") %>
<br>

<b>タスク作成日</b>
<%= @task.created_at.strftime("%Y-%m-%d %H:%M") %>
<br>

<b>ステータス</b>
<%= @task.status %>
<br>

<b>ラベル:</b>
<%= @task.labels.pluck(:label_name) %>
<br>


<b>優先順位</b>
<%= @task.priority %>
<br>
<br>
<%= link_to '一覧', tasks_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_with(model: @user, local: true) do |f| %> 
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "件のエラー") %> があります。 <%= @user.name %> from being saved:</h2>
  <ul>
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>

  <%= f.label :名前 %>
  <%= f.text_field :name %>

  <%= f.label :メールアドレス %>
  <%= f.email_field :email %>

  <%= f.label :パスワード %>
  <%= f.password_field :password %>

  <%= f.label :確認パスワード %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "登録" %>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<%= link_to 'タスク一覧', tasks_path %>